### ISSUE TITLE
No library used when decompiling P5R bmds

### ISSUE THREAD

**Issue by oceanstuck** [ShrineFox/AtlusScriptCompiler-GUI-Frontend#14]
Nothing is labeled when I decompile a bmd from P5R PC. Looking at the GUI code, it seems like the library isn't assigned...

**Comment by ShrineFox** [comment]
Thanks so much for pointing this out, I honestly can't remember the reasoning for restricting the library to only .FLOW for PC considering every other game uses the library for both. The output is way more readable this way. The latest release should fix this 👌
